name: EKS Angular DevOps Pipeline

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - kube

env:
  AWS_REGION: us-east-1
  ECR_REPO: eks-angular-repo

jobs:

  build_push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
          docker build -t angular-eks-app ./angular-app/angular-eks-app

    - name: Tag Image
      run: |
          docker tag angular-eks-app:latest \
          081139831993.dkr.ecr.us-east-1.amazonaws.com/eks-angular-repo:latest

    - name: Push Image
      run: |
          docker push \
          081139831993.dkr.ecr.us-east-1.amazonaws.com/eks-angular-repo:latest