name: Backend Build & Push

on:
  push:
    branches:
      - rahul

env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 081139831993
  ECR_REPO: demo-backend
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo
        run: |
          pwd
          ls -R

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./backend

      - name: Tag Image
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Push Image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG